[project]
name = "Today Qoute"
version = "1.0.0"
description = "Today Qoute"
requires-python = ">=3.10"
dependencies = [
    "flet-ads",
    "flet",
    "requests",
    "Pillow==10.4.0",
]


# for Android
[tool.flet.android.meta_data]
"com.google.android.gms.ads.APPLICATION_ID" = "ca-app-pub-3940256099942544~3347511713"

# for iOS
[tool.flet.ios.info]
GADApplicationIdentifier = "ca-app-pub-3940256099942544~3347511713"

# Docs: https://flet.dev/docs/publish
[tool.flet]
org = "com.today_qoute"
product = "Today Qoute"
company = "fady_dev"
copyright = "Copyright (C) 2025 by Flet"

[tool.flet.app]
path = "src"