[project]
name = "Today Qoute"
version = "1.0.0"
description = "flet-ads-example"
requires-python = ">=3.10"
dependencies = [
    "flet-ads",
    "flet",
    "requests"
]


# for Android
[tool.flet.android.meta_data]
"com.google.android.gms.ads.APPLICATION_ID" = "ca-app-pub-3940256099942544~3347511713"

# for iOS
[tool.flet.ios.info]
GADApplicationIdentifier = "ca-app-pub-3940256099942544~3347511713"

# Docs: https://flet.dev/docs/publish
[tool.flet]
org = "com.mycompany"
product = "flet-ads-example"
company = "Flet"
copyright = "Copyright (C) 2025 by Flet"

